<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AssemblyName>SlicerLauncher.Fusion</AssemblyName>
    <RootNamespace>SlicerLauncher.Fusion</RootNamespace>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <Authors>Nino King</Authors>
    <Company>3dprintkings</Company>
    <Product>SlicerLauncher Fusion Helper</Product>
    <Copyright>Copyright © 2026 Nino King · 3dprintkings</Copyright>
  </PropertyGroup>
</Project>
